const fs=require('fs'),http=require('http'),esbuild=require('esbuild'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
(async()=>{
 const bundle=await esbuild.build({entryPoints:['tests/browser/alerts.fixture.jsx'],bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'feed-test',setup(build){build.onResolve({filter:/upstox-live-feed$/},()=>({path:'feed',namespace:'qa'}));build.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:'export async function openUpstoxLiveFeed(){return ()=>{}}',loader:'js'}));}}]});
 const css=[...fs.readFileSync('app/layout.tsx','utf8').matchAll(/import "\.\/(.+\.css)"/g)].map(([,f])=>fs.readFileSync('app/'+f,'utf8')).join('\n').replace(/@import[^;]+;/g,'');
 const candles=Array.from({length:80},(_,i)=>({time:1782000000+i*86400,open:110,high:118,low:98,close:112,volume:1000}));
 let quotePrice=115,quoteTime=Date.now();
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url.startsWith('/api/upstox/quotes'))return res.end(JSON.stringify({ok:true,quotes:{'NSE_EQ|TEST':{lastPrice:quotePrice,lastTradeAt:new Date(quoteTime).toISOString()}}}));if(req.url.startsWith('/api/'))return res.end(JSON.stringify({ok:true,candles}));res.setHeader('Content-Type',req.url==='/qa.js'?'application/javascript':'text/html');res.end(req.url==='/qa.js'?bundle.outputFiles[0].text:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}\n.terminal-shell{display:block!important;height:100dvh}.price-chart-wrap,.price-chart,.chart-stack{height:650px!important}</style><div id="root"></div><script src="/qa.js"></script>`)}).listen(3225,'127.0.0.1');
 const browser=await chromium.launch({headless:true});try{
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install({time:new Date('2026-09-17T11:00:00+05:30')});await page.goto('http://127.0.0.1:3225');await page.waitForFunction(()=>window.qaSeries?.data().length===80);
  const open=()=>page.getByRole('button',{name:/Open alerts/}).click();
  await open();await page.getByRole('dialog',{name:'Alerts',exact:true}).waitFor();await page.getByRole('tab',{name:/Log/}).click();await page.getByText('No alert activity yet',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Create alert',exact:true}).click();await page.getByRole('radio',{name:/At or above/}).click();await page.getByRole('spinbutton',{name:'Alert price (₹)',exact:true}).fill('114');await page.getByRole('button',{name:'Create alert',exact:true}).click();
  await page.getByRole('tab',{name:/List/}).click();await page.locator('.price-alert-item').waitFor();assert.equal(await page.locator('.price-alert-item').count(),1);
  await page.getByRole('button',{name:'Create alert',exact:true}).click();await page.getByRole('radio',{name:/At or below/}).click();await page.getByRole('spinbutton',{name:'Alert price (₹)',exact:true}).fill('103.50');await page.getByRole('button',{name:'Create alert',exact:true}).click();assert.equal(await page.locator('.price-alert-item').count(),2);
  await page.getByLabel('Search alerts').fill('103.50');assert.equal(await page.locator('.price-alert-item').count(),1);await page.getByLabel('Clear alert search').click();
  if(process.env.ALERT_SCREENSHOTS)await page.screenshot({path:'outputs/alerts-list.png'});
  await page.getByLabel('Close price actions').click();await page.locator('[data-alert-price="114"]').waitFor();assert.equal(await page.locator('[data-alert-price]').count(),2);
  const level=page.locator('[data-alert-price="114"] line');const y=Number(await level.getAttribute('y1'));assert.equal(await level.getAttribute('stroke-dasharray'),'5 5');assert.equal(await page.locator('.chart-alert-levels rect').count(),0);
  await page.evaluate(()=>window.qaChart.priceScale('right').setVisibleRange({from:90,to:130}));await page.waitForFunction(old=>Number(document.querySelector('[data-alert-price="114"] line').getAttribute('y1'))!==old,y);
  if(process.env.ALERT_SCREENSHOTS)await page.screenshot({path:'outputs/alerts-chart.png'});
  await page.evaluate(()=>window.qaHidden(true));assert.equal(await page.locator('.chart-alert-levels').count(),0);await page.evaluate(()=>window.qaHidden(false));await page.locator('[data-alert-price="114"]').waitFor();
  await page.evaluate(()=>window.qaKey('NSE_EQ|OTHER'));await page.waitForFunction(()=>document.querySelectorAll('[data-alert-price]').length===0);await page.evaluate(()=>window.qaKey('NSE_EQ|TEST'));await page.locator('[data-alert-price="114"]').waitFor();
  await page.reload();await page.locator('[data-alert-price="114"]').waitFor();console.log('Alerts persist, show only on their symbol, track price-scale changes and respect the eye switch');
  await open();await page.getByRole('button',{name:'Cancel alert for TEST at 103.5'}).click();assert.equal(await page.locator('.price-alert-item').count(),1);await page.getByRole('tab',{name:/Log/}).click();await page.getByText('Cancelled',{exact:true}).waitFor();
  await page.getByLabel('Close price actions').click();quoteTime=await page.evaluate(()=>Date.now());await page.evaluate(()=>window.qaMarket(true));await page.clock.fastForward(10000);await page.waitForFunction(()=>JSON.parse(localStorage.getItem('papertrade-price-tasks-v1:local')).some(t=>t.status==='triggered'));await open();await page.getByRole('tab',{name:/Log/}).click();await page.getByText('Triggered',{exact:true}).waitFor();assert.equal(await page.locator('[data-alert-price]').count(),0);console.log('Cancellation and fresh quote triggers move items into Log and remove their chart lines');
  await page.evaluate(()=>window.qaTheme('neon'));if(process.env.ALERT_SCREENSHOTS)await page.screenshot({path:'outputs/alerts-log-dark.png'});
  await page.getByRole('button',{name:'Create alert',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.price-alert-form input')?.value==='110.00');if(process.env.ALERT_SCREENSHOTS)await page.screenshot({path:'outputs/alerts-create-dark.png'});
  await page.getByRole('radio',{name:/At or above/}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('radio',{name:/At or below/}).getAttribute('aria-checked'),'true');await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Alerts',exact:true}).waitFor();await page.keyboard.press('Escape');
  for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});const center=await page.locator('.chart-positions-trigger').boundingBox(),row=await page.locator('.chart-trade-meta').boundingBox(),icon=await page.locator('.price-tasks-button').boundingBox();assert.ok(Math.abs(center.x+center.width/2-row.x-row.width/2)<1,'Stocks stays centered');assert.ok(icon.x>=center.x+center.width&&icon.x+icon.width<=row.x+row.width+1);assert.ok(Math.abs(icon.y+icon.height/2-center.y-center.height/2)<1,'Icon shares the Stocks row');await open();const box=await page.getByRole('dialog').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);await page.getByLabel('Close price actions').click();}
  await page.evaluate(()=>window.qaOrder());await page.getByLabel('Quantity',{exact:true}).fill('0');await page.getByRole('button',{name:'Confirm paper order'}).click();await page.getByRole('alert').waitFor();await page.getByLabel('Quantity',{exact:true}).fill('2');await page.getByRole('button',{name:'Confirm paper order'}).click();quotePrice=110;quoteTime=await page.evaluate(()=>Date.now());await page.clock.fastForward(10000);await page.waitForFunction(()=>window.qaFills?.length===1);assert.equal(await page.evaluate(()=>window.qaFills[0].price),110);console.log('Icon far right, Stocks centered at four widths; theme, keyboard, quantity validation and paper-order fills pass');
  assert.equal(errors.length,0,errors.join('\n'));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
