const fs=require('fs'),http=require('http'),esbuild=require('esbuild'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
(async()=>{
 const build=await esbuild.build({entryPoints:['tests/browser/indicator-studio.fixture.jsx'],bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'feed',setup(b){b.onResolve({filter:/upstox-live-feed$/},()=>({path:'feed',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:'export async function openUpstoxLiveFeed(o){window.qaFeed=o.onTick;return ()=>{}}',loader:'js'}));}}]});
 const css=[...fs.readFileSync('app/layout.tsx','utf8').matchAll(/import "\.\/(.+\.css)"/g)].map(([,f])=>fs.readFileSync('app/'+f,'utf8')).join('\n').replace(/@import[^;]+;/g,'');
 const start=Date.parse('2026-09-18T09:15:00+05:30')/1000,candles=Array.from({length:330},(_,i)=>{const close=100+i*.03+4*Math.sin(i/9);return {time:start+i*300,open:close-.3,high:close+1,low:close-1,close,volume:1000+i*7};});
 const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({ok:true,candles,quotes:{},segments:['historical']}));}res.setHeader('Content-Type',req.url==='/qa.js'?'application/javascript':'text/html');res.end(req.url==='/qa.js'?build.outputFiles[0].text:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}.price-chart-wrap,.price-chart,.chart-stack{height:100%!important}</style><div id="root"></div><script src="/qa.js"></script>`);}).listen(3235,'127.0.0.1');
 const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3235');await page.waitForFunction(()=>window.qaCandles?.data().length>300);
 const open=async()=>{await page.getByRole('button',{name:'Functions',exact:true}).click();await page.getByRole('dialog',{name:'Functions',exact:true}).waitFor();},search=q=>page.getByLabel('Search indicators').fill(q);
 await open();await search('RSI');await page.getByRole('button',{name:'Add Relative Strength Index',exact:true}).click();await search('directional');await page.getByRole('button',{name:'Add Average Directional Index',exact:true}).click();
 await page.getByRole('button',{name:'Close functions'}).click();await page.waitForFunction(()=>window.qaChart.panes().length===3);await page.waitForTimeout(300);await page.screenshot({path:'outputs/indicator-panes.png'});
 const rsiBefore=await page.evaluate(()=>window.qaStudies.bundles.find(b=>b.id==='rsi').series[0].data().at(-1).value);
 await open();await search('RSI');await page.getByRole('dialog',{name:'Functions',exact:true}).getByRole('button',{name:'Settings for Relative Strength Index',exact:true}).click();const editor=page.getByRole('dialog',{name:'Relative Strength Index settings',exact:true});await editor.waitFor();
 await editor.getByLabel('Length',{exact:true}).fill('7');await editor.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Close functions'}).click();
 await page.waitForFunction(before=>window.qaStudies.bundles.find(b=>b.id==='rsi').series[0].data().at(-1).value!==before,rsiBefore);
 await page.getByRole('button',{name:'Indicator actions for Relative Strength Index',exact:true}).dblclick();await editor.getByRole('button',{name:'Style',exact:true}).click();await editor.getByLabel('Plot 1 color',{exact:true}).fill('#ff8800');await editor.getByRole('button',{name:'Line width',exact:true}).click();await page.getByRole('option',{name:'3 px',exact:true}).click();await editor.getByRole('button',{name:'Apply',exact:true}).click();
 await page.waitForFunction(()=>window.qaStudies.bundles.find(b=>b.id==='rsi').series[0].options().lineWidth===3);
 assert.match(await page.evaluate(()=>window.qaStudies.bundles.find(b=>b.id==='rsi').series[0].options().color),/#ff8800/);
 await page.reload();await page.waitForFunction(()=>window.qaStudies?.bundles.find(b=>b.id==='rsi')?.config.inputs.length===7);assert.equal(await page.evaluate(()=>window.qaChart.panes().length),3);
 await page.getByRole('button',{name:'Indicator actions for Relative Strength Index',exact:true}).dblclick();await editor.getByLabel('Length',{exact:true}).fill('12');await editor.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.evaluate(()=>window.qaStudies.bundles.find(b=>b.id==='rsi').config.inputs.length),7);
 await page.getByRole('button',{name:'Hide RSI 7',exact:true}).click();await page.waitForFunction(()=>window.qaChart.panes().length===2);await open();await search('RSI');await page.getByRole('button',{name:'Show Relative Strength Index',exact:true}).click();await page.getByRole('dialog',{name:'Functions',exact:true}).getByRole('button',{name:'Settings for Relative Strength Index',exact:true}).click();await editor.getByRole('button',{name:'Visibility',exact:true}).click();await editor.getByRole('button',{name:'1D',exact:true}).click();await editor.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Close functions'}).click();await page.waitForFunction(()=>!window.qaStudies.bundles.some(b=>b.id==='rsi'));
 await open();await search('Average Directional');await page.getByRole('dialog',{name:'Functions',exact:true}).getByRole('button',{name:'Settings for Average Directional Index',exact:true}).click();const adx=page.getByRole('dialog',{name:'Average Directional Index settings'});await adx.getByLabel('DI length',{exact:true}).fill('0');await adx.getByRole('button',{name:'Apply',exact:true}).click();await adx.getByRole('alert').waitFor();await adx.getByLabel('DI length',{exact:true}).fill('10');await page.screenshot({path:'outputs/indicator-inputs.png'});await adx.getByRole('button',{name:'Cancel',exact:true}).click();
 await search('');for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});const panel=page.getByRole('dialog',{name:'Functions',exact:true});assert.equal(await panel.evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(width===390)await page.screenshot({path:'outputs/indicator-library.png'});}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Close functions'}).click();await page.getByRole('button',{name:'Theme',exact:true}).click();await open();await page.screenshot({path:'outputs/indicator-dark.png'});await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Functions',exact:true}).waitFor({state:'hidden'});
 // Exercise a real comparison fetch and exact-alignment result in the browser.
 await open();await search('Ratio');await page.getByRole('button',{name:'Add Ratio',exact:true}).click();await page.getByRole('dialog',{name:'Functions',exact:true}).getByRole('button',{name:'Settings for Ratio',exact:true}).click();const ratioEditor=page.getByRole('dialog',{name:'Ratio settings',exact:true});await ratioEditor.getByRole('button',{name:'Comparison symbol',exact:true}).click();await page.getByRole('option',{name:'NIFTY 50',exact:true}).click();await ratioEditor.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Close functions'}).click();await page.waitForFunction(()=>window.qaStudies.bundles.find(b=>b.id==='ratio')?.result.plots[0]?.values.some(v=>v===1));
 // Rendering every supported type catches API-level failures that arithmetic tests cannot.
 await page.evaluate(()=>window.qaIndicators({}));
 for(const id of ['volume','macd','stochastic','dmi','bollinger','supertrend','ichimoku','vpvr','sar','fractals','zigzag','guppy','coppock','smi']){
  await page.evaluate(id=>window.qaIndicators({[id]:true}),id);await page.waitForFunction(id=>window.qaStudies.bundles.length===1&&window.qaStudies.bundles[0].id===id,id);await page.waitForTimeout(50);
  assert.ok(await page.evaluate(()=>window.qaStudies.bundles[0].series.length>0),id);
 }
 await page.evaluate(()=>window.qaIndicators({rsi:true,adx:true,macd:true,volume:true}));await page.waitForTimeout(100);await page.evaluate(()=>window.qaIndicators({adx:true,macd:true}));await page.waitForFunction(()=>window.qaChart.panes().length===3);
 // Compact transparent headings, with actions immediately beside the title.
 const heading=page.locator('.study-pane-heading').first();
 assert.equal(await heading.locator('button').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');
 assert.ok(await heading.evaluate(e=>e.children[1].getBoundingClientRect().left-e.children[0].getBoundingClientRect().right<10));
 await heading.locator('.study-pane-title').click();await page.getByRole('button',{name:'Remove indicator',exact:true}).waitFor();
 assert.equal(await page.locator('.indicator-editor').count(),0);
 await page.getByRole('button',{name:'Close indicator actions'}).click();
 await heading.locator('.study-pane-title').dblclick();await page.getByRole('dialog',{name:'Average Directional Index settings'}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.evaluate(()=>window.qaIndicators({ema21:true}));await page.waitForFunction(()=>window.qaStudies.bundles.length===1&&window.qaStudies.bundles[0].id==='ema21');await page.waitForTimeout(300);
 const linePoint=()=>page.evaluate(()=>{const b=window.qaStudies.bundles[0],s=b.series[0],scale=window.qaChart.timeScale(),rect=window.qaChart.panes()[0].getHTMLElement().getBoundingClientRect();const d=s.data().filter(p=>p.value!==undefined&&scale.timeToCoordinate(p.time)>50&&scale.timeToCoordinate(p.time)<scale.width()-50);const p=d[Math.floor(d.length/2)];return {x:rect.left+scale.timeToCoordinate(p.time),y:rect.top+s.priceToCoordinate(p.value)};});
 let point=await linePoint();await page.touchscreen.tap(point.x,point.y);await page.getByRole('button',{name:'Remove indicator',exact:true}).waitFor();
 assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.evaluate(()=>window.qaStudies.bundles.length),1);
 await page.getByRole('button',{name:'Close indicator actions'}).click();
 point=await linePoint();await page.touchscreen.tap(point.x,point.y);await page.touchscreen.tap(point.x,point.y);await page.getByRole('dialog',{name:/settings$/}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:/Indicator actions for EMA/}).dblclick();await page.getByRole('dialog',{name:/settings$/}).waitFor();await page.getByRole('button',{name:'Cancel',exact:true}).click();
 // A drag across the line is chart navigation, not an indicator tap.
 point=await linePoint();await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+50,point.y+20,{steps:10});await page.mouse.up();assert.equal(await page.locator('.study-quick-actions').count(),0);assert.equal(await page.getByRole('dialog').count(),0);
 await page.evaluate(()=>window.qaTool('trend-line'));await page.locator('.is-drawing').waitFor();point=await linePoint();await page.touchscreen.tap(point.x,point.y);assert.equal(await page.locator('.study-quick-actions').count(),0);await page.keyboard.press('Escape');await page.evaluate(()=>window.qaTool('cursor'));
 await page.getByRole('button',{name:/Indicator actions for EMA/}).click();await page.getByRole('button',{name:'Remove indicator',exact:true}).click();await page.waitForFunction(()=>window.qaStudies.bundles.length===0);
 assert.deepEqual(errors,[]);console.log('Indicator studio: calculations/settings/panes, transparent compact controls, name and plotted-line single/double taps, drag/drawing safety and explicit removal pass');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
