const fs=require('fs'),http=require('http'),esbuild=require('esbuild'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const base={symbol:'ALPHA',name:'Alpha Technologies IPO',status:'open',issueType:'regular',industry:'Technology',issueSizeCrore:250,minimumPrice:100,maximumPrice:110,biddingStartDate:'2026-09-15',biddingEndDate:'2026-09-18',totalSubscription:2.54,gmpAmount:5,gmpPercent:4.55,gmpUpdatedAt:'',gmpCheckedAt:'2026-09-18T04:30:00Z',gmpSource:'ipogram',details:{allotmentDate:'2026-09-21',listingDate:'2026-09-23',dailyEndTime:'17:00:00'}};
const seed=[{...base,id:'alpha'},{...base,id:'upcoming',name:'Beta Industries IPO',status:'upcoming',biddingStartDate:'2026-09-22',biddingEndDate:'2026-09-25',gmpAmount:null,gmpPercent:null},{...base,id:'waiting',name:'Gamma Finance IPO',status:'closed',biddingEndDate:'2026-09-16',gmpAmount:-5,gmpPercent:-4.55},{...base,id:'allotted',name:'Delta Manufacturing IPO',status:'closed',biddingEndDate:'2026-09-16',gmpAmount:0,gmpPercent:0,details:{...base.details,allotmentPublished:true,registrarName:'Verified Registrar',registrarUrl:'https://example.com/result'}},{...base,id:'listed',name:'Epsilon IPO',status:'listed',details:{...base.details,listingDate:'2026-09-10',listingPrice:120,issuePrice:110}},{...base,id:'sme',name:'Small Enterprise IPO',issueType:'sme'}];
(async()=>{
 const bundle=await esbuild.build({entryPoints:['tests/browser/ipo.fixture.jsx'],bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'}});
 const css=[...fs.readFileSync('app/layout.tsx','utf8').matchAll(/import "\.\/(.+\.css)"/g)].map(([,f])=>fs.readFileSync('app/'+f,'utf8')).join('\n').replace(/@import[^;]+;/g,'');
 let rows=seed,fail=false,demandCalls=0;
 const server=http.createServer((req,res)=>{
  if(req.url.startsWith('/api/')){res.setHeader('Content-Type','application/json');if(req.url.startsWith('/api/upstox/ipos')){res.statusCode=fail?503:200;res.end(JSON.stringify(fail?{ok:false,error:{message:'Feed temporarily unavailable'}}:{ok:true,ipos:rows,fetchedAt:'2026-09-18T04:35:00Z'}));}else if(req.url.startsWith('/api/ipo-chances')){demandCalls++;res.end(JSON.stringify({ok:false}));}else res.end(JSON.stringify({entries:[]}));return;}
  res.setHeader('Content-Type',req.url==='/qa.js'?'application/javascript':'text/html');res.end(req.url==='/qa.js'?bundle.outputFiles[0].text:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}\n.terminal-shell{display:block!important;height:auto!important;min-height:100vh!important;overflow:visible!important}html,body,#root{height:auto!important;overflow:visible!important}.terminal-shell .ipo-modal{max-height:none!important;overflow:visible!important;max-width:1120px;width:100%;margin:auto;padding:18px;box-sizing:border-box}</style><div id="root"></div><script src="/qa.js"></script>`);
 }).listen(3227,'127.0.0.1');
 const browser=await chromium.launch({headless:true});try{
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.setFixedTime(new Date('2026-09-18T06:00:00Z'));
  await page.addInitScript(()=>localStorage.setItem('papertrade-ipo-alerts-enabled-v1','false'));
  const cards=()=>page.locator('.ipo-compact-card');const status=name=>page.getByRole('group',{name:'IPO status'}).getByRole('button',{name:new RegExp('^'+name)});
  await page.goto('http://127.0.0.1:3227');await cards().first().waitFor();assert.equal(await cards().count(),1);assert.equal(await cards().first().getAttribute('data-ipo-id'),'alpha');await page.getByText('Closes today',{exact:true}).waitFor();assert.equal(await page.locator('.ipo-compact-gmp.high').count(),1);assert.match(await page.locator('.ipo-gmp-source').textContent(),/Checked.*source update time unavailable/);
  await page.getByLabel('Save Alpha Technologies IPO',{exact:true}).click();await page.getByRole('tab',{name:/Saved/}).click();assert.equal(await cards().count(),1);await page.reload();await cards().first().waitFor();assert.equal(await page.getByRole('tab',{name:/Saved/}).getAttribute('aria-selected'),'true');assert.equal(await page.getByLabel('Unsave Alpha Technologies IPO').count(),1);
  await page.evaluate(()=>window.qaOwner('other'));await page.getByRole('heading',{name:'Keep the IPOs you want to follow'}).waitFor();assert.equal(await cards().count(),0);await page.evaluate(()=>window.qaOwner('qa'));await cards().first().waitFor();
  await page.getByRole('tab',{name:'Explore',exact:true}).click();await status('Allotment').click();assert.equal(await cards().count(),2);assert.equal(await page.locator('.ipo-compact-gmp.low').count(),1);assert.equal(await page.locator('.ipo-compact-gmp.neutral').count(),1);await status('Upcoming').click();assert.equal(await cards().count(),1);await status('Listed').click();assert.equal(await cards().count(),1);assert.match(await page.locator('.ipo-listing-result').textContent(),/9.09%/);
  await page.getByRole('button',{name:'Sort IPOs',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.getByRole('option',{name:/^Next event/}).evaluate(e=>e===document.activeElement),true);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.match(await page.getByRole('button',{name:'Sort IPOs',exact:true}).textContent(),/Company name/);await page.reload();await cards().first().waitFor();assert.equal(await status('Listed').getAttribute('aria-pressed'),'true');assert.match(await page.getByRole('button',{name:'Sort IPOs',exact:true}).textContent(),/Company name/);
  await page.getByRole('button',{name:'Sort IPOs',exact:true}).click();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'Sort IPOs',exact:true}).evaluate(e=>e===document.activeElement),true);
  await page.getByRole('tab',{name:'Calendar',exact:true}).click();await page.getByRole('button',{name:'2026-09-21: 5 IPO events',exact:true}).click();assert.equal(await page.locator('.ipo-agenda > button').count(),5);assert.match(await page.locator('.ipo-agenda').textContent(),/Expected allotment/);await page.locator('.ipo-agenda > button').first().click();await page.getByRole('heading',{name:'Alpha Technologies'}).waitFor();assert.equal(await page.locator('.ipo-timeline-disclosure').getAttribute('open'),null);await page.locator('.ipo-timeline-disclosure summary').click();await page.getByText('A scheduled allotment date does not prove',{exact:false}).waitFor();if(process.env.IPO_SCREENSHOTS)await page.screenshot({path:'outputs/ipo-detail-timeline.png',fullPage:true});await page.getByRole('button',{name:'Back to IPOs'}).click();assert.equal(await page.locator('.ipo-agenda > button').count(),5);
  await page.getByRole('tab',{name:'Explore',exact:true}).click();await status('Open').click();await page.getByRole('button',{name:'SME',exact:true}).click();const before=demandCalls;await cards().getByRole('button',{name:'Details',exact:true}).click();await page.getByText('SME category rules differ from Mainboard.',{exact:false}).waitFor();assert.equal(demandCalls,before);await page.getByRole('button',{name:'Back to IPOs'}).click();await page.getByRole('button',{name:'Mainboard',exact:true}).click();
  fail=true;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByText('Feed temporarily unavailable',{exact:true}).waitFor();assert.equal(await cards().count(),1);fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByText('Feed temporarily unavailable',{exact:true}).waitFor({state:'hidden'});
  for(const theme of ['light','neon'])for(const width of [320,390,768,1280]){await page.evaluate(t=>window.qaTheme(t),theme);await page.setViewportSize({width,height:844});for(const tab of ['Explore','Calendar']){await page.getByRole('tab',{name:tab,exact:true}).click();await page.waitForTimeout(180);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${theme} ${width} ${tab} overflow`);if(process.env.IPO_SCREENSHOTS&&[390,1280].includes(width))await page.screenshot({path:`outputs/ipo-${theme}-${width}-${tab.toLowerCase()}.png`,fullPage:true});}await page.getByRole('tab',{name:'Explore',exact:true}).click();await page.getByRole('button',{name:'Sort IPOs',exact:true}).click();const bounds=await page.getByRole('dialog').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width+1&&bounds.y>=0&&bounds.y+bounds.height<=845);if(process.env.IPO_SCREENSHOTS&&width===390)await page.screenshot({path:`outputs/ipo-${theme}-selector.png`});await page.keyboard.press('Escape');const sortBox=await page.getByRole('button',{name:'Sort IPOs',exact:true}).boundingBox(),searchBox=await page.getByRole('button',{name:'Search IPOs',exact:true}).boundingBox();assert.ok(searchBox.x>=sortBox.x+sortBox.width&&Math.abs(searchBox.width-searchBox.height)<1,JSON.stringify({width,theme,sortBox,searchBox}));await page.getByRole('button',{name:'Search IPOs',exact:true}).click();const sb=await page.locator('.ipo-search-dialog').boundingBox();assert.ok(sb.x>=0&&sb.x+sb.width<=width+1&&sb.y+sb.height<=844);if(process.env.IPO_SCREENSHOTS&&width===390)await page.screenshot({path:`outputs/ipo-${theme}-search.png`});await page.keyboard.press('Escape');}
  rows=seed.filter(x=>x.id!=='alpha');await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.getByRole('heading',{name:'No matching IPOs',exact:true}).waitFor();await page.getByRole('tab',{name:/Saved/}).click();await page.getByText('Not in the latest feed. No current status assumed.',{exact:true}).waitFor();assert.equal(await page.getByLabel('Remove saved Alpha Technologies IPO').count(),1);assert.deepEqual(errors,[]);
  console.log('IPO: status accuracy, saved/account persistence, calendar/detail return, keyboard selectors, SME honesty, GMP sources, retries, missing saved records and both themes at four widths pass');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
