"use client";
import { Activity, Camera, Crosshair, Expand, Grid3X3, Radio, Scan, X, ZoomIn, ZoomOut, Search, Star, Check, Settings2, Eye, EyeOff, SlidersHorizontal } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { ChartAction, ChartIndicators, DrawingTool } from './MarketChart';
import { STUDIES, studyDefaults, studyTitle } from '@/lib/indicator-catalog';
import { useIndicatorSettings } from '@/lib/indicator-settings';
import { IndicatorSettings } from './IndicatorSettings';
import { useTransientBack } from './useTransientBack';
export function ChartFunctionMenu({indicators,onToggleIndicator,onAction,onClose,onDrawing,excluded=[]}:{indicators:ChartIndicators;onToggleIndicator:(id:keyof ChartIndicators)=>void;onAction:(action:ChartAction)=>void;onClose:()=>void;onDrawing?:(id:DrawingTool)=>void;excluded?:string[]}){
 const [tab,setTab]=useState('All'),[query,setQuery]=useState(''),[group,setGroup]=useState('All types'),[editing,setEditing]=useState<string|null>(null),[controls,setControls]=useState(false),[notice,setNotice]=useState('');
 const {settings,setStudy,favorites,toggleFavorite}=useIndicatorSettings(),panel=useRef<HTMLElement>(null);
 useTransientBack(true,onClose);useEffect(()=>{const old=document.activeElement as HTMLElement;panel.current?.focus();return()=>{if(old?.isConnected)old.focus();};},[]);
 const list=STUDIES.filter(s=>!excluded.includes(s.id)&&(tab!=='Favourites'||favorites.includes(s.id))&&(tab!=='On chart'||indicators[s.id])&&(group==='All types'||s.group===group)&&`${s.name} ${s.id} ${s.group}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));
 function toggle(id:string){const study=STUDIES.find(s=>s.id===id)!;if(!indicators[id]&&!study.overlay&&STUDIES.filter(s=>!s.overlay&&indicators[s.id]&&!settings[s.id]?.hidden).length>=6){setNotice('Six lower panes are already active. Hide or remove one before adding another.');return;}setNotice('');onToggleIndicator(id);}
 function apply(id:string){
  const study=STUDIES.find(s=>s.id===id)!;if(study.unavailable)return;
  const config=settings[id]??studyDefaults(id);
  if((!indicators[id]||config.hidden)&&!study.overlay&&STUDIES.filter(s=>!s.overlay&&indicators[s.id]&&!settings[s.id]?.hidden).length>=6){setNotice('Six lower panes are already active. Hide or remove one before adding another.');return;}
  if(config.hidden)setStudy(id,{...config,hidden:false});
  if(!indicators[id])onToggleIndicator(id);
  setNotice(study.name+' applied to chart');
 }
 return <div className="chart-function-backdrop indicator-studio-backdrop" onPointerDown={onClose}><section ref={panel} tabIndex={-1} className="chart-function-menu indicator-studio" role="dialog" aria-modal="true" aria-label="Functions" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key!=='Tab'||editing)return;const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input')??[]).filter(el=>el.getClientRects().length);if(e.shiftKey&&(document.activeElement===nodes[0]||document.activeElement===panel.current)){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}>
 <div className="indicator-grip"/><header><div><Activity size={22}/><span><b>Indicators</b><small>Your chart. Your way.</small></span></div><button aria-label="Close functions" onClick={onClose}><X size={21}/></button></header><label className="indicator-search"><Search size={19}/><input aria-label="Search indicators" placeholder="Search RSI, ADX, moving averages…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear indicator search" onClick={()=>setQuery('')}><X size={16}/></button>}</label>
 <nav className="indicator-tabs" aria-label="Indicator lists">{['All','Favourites','On chart'].map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}{t==='On chart'&&<small>{Object.values(indicators).filter(Boolean).length}</small>}</button>)}</nav><nav className="indicator-groups" aria-label="Indicator categories">{['All types','Trend','Momentum','Volume','Volatility','Price','Learning','Comparison','Market breadth'].map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</button>)}</nav>
 <div className="indicator-studio-body">{notice&&<p role="status" className="indicator-help">{notice}</p>}{onDrawing&&tab==='All'&&(!query||'volume profile fixed range'.includes(query.toLowerCase()))&&(group==='All types'||group==='Volume')&&<button className="indicator-drawing-link" onClick={()=>{onDrawing('volume-profile');onClose();}}><SlidersHorizontal size={18}/><span><b>Volume Profile Fixed Range</b><small>Choose a range with the drawing tool</small></span></button>}
 {list.map(s=>{const config=settings[s.id]??studyDefaults(s.id),added=indicators[s.id];return <article className={`indicator-card ${added?'added':''}`} key={s.id}><button className={`indicator-star ${favorites.includes(s.id)?'saved':''}`} aria-label={`${favorites.includes(s.id)?'Unfavorite':'Favorite'} ${s.name}`} onClick={()=>toggleFavorite(s.id)}><Star size={17} fill={favorites.includes(s.id)?'currentColor':'none'}/></button><button className="indicator-card-name" disabled={!!s.unavailable} aria-label={`Apply ${s.name}`} aria-pressed={!!added&&!config.hidden} onClick={()=>apply(s.id)}><b>{studyTitle(s.id,config)}</b><small>{s.unavailable??`${s.group} · ${s.overlay?'On price chart':'Separate pane'}${added&&config.hidden?' · Hidden':''}`}</small>{added&&!config.hidden&&<span className="indicator-applied"><Check size={12}/>Applied</span>}</button>{!s.unavailable&&<div className="indicator-card-actions">{added&&s.id!=='smc'&&<button aria-label={`${config.hidden?'Show':'Hide'} ${s.name}`} onClick={()=>setStudy(s.id,{...config,hidden:!config.hidden})}>{config.hidden?<EyeOff size={18}/>:<Eye size={18}/>}</button>}{s.id!=='smc'&&<button aria-label={`Settings for ${s.name}`} onClick={()=>setEditing(s.id)}><Settings2 size={18}/></button>}<>{added&&<button className="indicator-remove" aria-label={`Remove ${s.name}`} onClick={()=>toggle(s.id)}><X size={18}/></button>}</></div>}</article>;})}{!list.length&&<p className="indicator-empty">{tab==='On chart'?'Your chart is clear. Add an indicator from All.':'No matching indicators.'}</p>}</div>
 <footer><button className="indicator-chart-controls" aria-expanded={controls} onClick={()=>setControls(v=>!v)}><SlidersHorizontal size={17}/>Chart controls</button><small>Settings saved on this device</small></footer>
 {controls&&<div className="indicator-controls-panel"><header><b>Chart controls</b><button aria-label="Close chart controls" onClick={()=>setControls(false)}><X size={18}/></button></header><div className="chart-function-grid">{([['fit','Fit all data',Scan],['live','Go to live',Radio],['zoom-in','Zoom in',ZoomIn],['zoom-out','Zoom out',ZoomOut],['toggle-grid','Toggle grid',Grid3X3],['toggle-crosshair','Toggle crosshair',Crosshair],['screenshot','Save image',Camera],['reset','Reset view',Expand]] as const).map(([action,label,Icon])=><button key={action} onClick={()=>onAction(action)}><Icon size={18}/>{label}</button>)}</div><div className="chart-scale-options">{(['normal','log','percent','indexed'] as const).map(s=><button key={s} onClick={()=>onAction(`scale-${s}`)}>{s==='indexed'?'Indexed 100':s==='log'?'Logarithmic':s==='percent'?'Percentage':'Normal'}</button>)}</div></div>}
 </section>{editing&&<IndicatorSettings key={editing} id={editing} onClose={()=>setEditing(null)}/>}</div>;
}
