"use client";
import { useRef, useState, useEffect } from 'react';
import { X, RotateCcw, Check } from 'lucide-react';
import { STUDIES, SOURCES, TIMEFRAMES, normalizeStudy, studyDefaults, studyTitle } from '@/lib/indicator-catalog';
import { useIndicatorSettings } from '@/lib/indicator-settings';
import { ModernSelect } from './ModernSelect';
import { useTransientBack } from './useTransientBack';
import { instruments } from '@/lib/market';
export function IndicatorSettings({id,onClose}:{id:string;onClose:()=>void}){
 const {settings,setStudy}=useIndicatorSettings(),[draft,setDraft]=useState(()=>structuredClone(settings[id]??studyDefaults(id))),[tab,setTab]=useState('Inputs'),[error,setError]=useState('');
 const definition=STUDIES.find(s=>s.id===id)!,panel=useRef<HTMLElement>(null);
 const comparisonChoices=[{value:'',label:'Choose a symbol'},{value:'NSE_INDEX|Nifty 50',label:'NIFTY 50'},{value:'NSE_INDEX|Nifty Bank',label:'BANK NIFTY'},...instruments.map(s=>({value:s.instrumentKey,label:s.symbol}))];
 useTransientBack(true,onClose);
 useEffect(()=>setError(''),[draft]);
 useEffect(()=>{const old=document.activeElement as HTMLElement;panel.current?.focus();return()=>{if(old?.isConnected)old.focus();};},[]);
 function save(){for(const f of definition.fields){const n=draft.inputs[f.key];if(!Number.isFinite(n)||n<(f.min??1)||n>(f.max??500)||(f.step===1&&!Number.isInteger(n))){setError(`${f.label}: enter ${f.step===1?'a whole number':'a number'} from ${f.min??1} to ${f.max??500}.`);return;}}if(draft.inputs.fast&&draft.inputs.slow&&draft.inputs.fast>=draft.inputs.slow&&!['ma-ema-cross','kama'].includes(id)){setError('Fast length must be smaller than slow length.');return;}if(id==='rsi'&&draft.inputs.lower>=draft.inputs.upper){setError('Lower level must be below the upper level.');return;}if(id==='sar'&&draft.inputs.start>draft.inputs.maximum){setError('Start must not exceed Maximum.');return;}setStudy(id,normalizeStudy(id,draft));onClose();}
 return <div className="indicator-editor-backdrop" onPointerDown={onClose}><section className="indicator-editor" role="dialog" aria-modal="true" aria-label={`${definition.name} settings`} ref={panel} tabIndex={-1} onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button,input,[tabindex="0"]')??[]).filter(el=>el.getClientRects().length);if(e.shiftKey&&(document.activeElement===nodes[0]||document.activeElement===panel.current)){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}>
 <div className="indicator-grip"/><header><div><small>MAKE IT YOURS</small><h2>{studyTitle(id,draft)}</h2></div><button aria-label="Close indicator settings" onClick={onClose}><X size={21}/></button></header><nav className="indicator-tabs" aria-label="Indicator settings tabs">{['Inputs','Style','Visibility'].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <div className="indicator-editor-body">{tab==='Inputs'&&<>{definition.comparison&&<ModernSelect label="Comparison symbol" value={draft.comparisonKey??''} choices={comparisonChoices} onChange={comparisonKey=>setDraft({...draft,comparisonKey})}/>} {definition.fields.map(f=><label className="indicator-input" key={f.key}><span>{f.label}</span><input aria-label={f.label} type="number" inputMode={f.step===1?'numeric':'decimal'} min={f.min??1} max={f.max??500} step={f.step??1} value={Number.isNaN(draft.inputs[f.key])?'':draft.inputs[f.key]} onChange={e=>setDraft({...draft,inputs:{...draft.inputs,[f.key]:e.target.value===''?Number.NaN:Number(e.target.value)}})}/></label>)}
 {/^(ema|sma|ma$|wma|smma|dema|tema|hma|alma|hamming|kama|mcginley|lsma|linreg|slope|stderr|rsi|macd|bollinger|bbp|bbw|momentum|roc|stddev|tsi|smi|trix)/.test(id)&&<ModernSelect label="Source" value={draft.source} choices={SOURCES.map(s=>({value:s,label:s.toUpperCase()}))} onChange={source=>setDraft({...draft,source})}/>}
 {id==='rsi'&&<ModernSelect label="Smoothing line" value={draft.smoothing} choices={['None','SMA','EMA','RMA','WMA'].map(s=>({value:s,label:s}))} onChange={smoothing=>setDraft({...draft,smoothing})}/>}{!definition.fields.length&&<p className="indicator-help">No length inputs are needed. Style and timeframe visibility can still be changed.</p>}{definition.note&&<p className="indicator-help">{definition.note}</p>}<p className="indicator-help">Changes apply when you tap Apply. Technical alert rules keep their own saved settings.</p></>}
 {tab==='Style'&&<><p className="indicator-help">Colours follow the study’s output order. Unused plot colours are reserved for additional lines.</p><div className="indicator-colors">{draft.colors.map((color,i)=><label key={i}><span>Plot {i+1}</span><input aria-label={`Plot ${i+1} color`} type="color" value={color} onChange={e=>setDraft({...draft,colors:draft.colors.map((c,j)=>i===j?e.target.value:c)})}/></label>)}</div><ModernSelect label="Line width" value={String(draft.width)} choices={[1,2,3,4].map(n=>({value:String(n),label:`${n} px`}))} onChange={v=>setDraft({...draft,width:Number(v)})}/><ModernSelect label="Line style" value={String(draft.dash)} choices={['Solid','Dotted','Dashed','Large dashed','Sparse dotted'].map((s,i)=>({value:String(i),label:s}))} onChange={v=>setDraft({...draft,dash:Number(v)})}/><label className="indicator-input"><span>Opacity</span><input aria-label="Opacity" type="range" min="10" max="100" value={draft.opacity} onChange={e=>setDraft({...draft,opacity:Number(e.target.value)})}/><b>{draft.opacity}%</b></label><label className="indicator-check"><input type="checkbox" checked={draft.showValue} onChange={e=>setDraft({...draft,showValue:e.target.checked})}/>Show latest value on price scale</label></>}
 {tab==='Visibility'&&<><label className="indicator-check"><input type="checkbox" checked={!draft.hidden} onChange={e=>setDraft({...draft,hidden:!e.target.checked})}/>Show on chart</label><p className="indicator-help">Select specific timeframes, or leave all unselected for every timeframe.</p><div className="indicator-timeframes">{TIMEFRAMES.map(t=><button key={t} aria-pressed={draft.timeframes.includes(t)} onClick={()=>setDraft({...draft,timeframes:draft.timeframes.includes(t)?draft.timeframes.filter(v=>v!==t):[...draft.timeframes,t]})}>{t}</button>)}</div></>}{error&&<p role="alert" className="indicator-error">{error}</p>}</div>
 <footer><button className="indicator-reset" onClick={()=>{setDraft(studyDefaults(id));setError('');}}><RotateCcw size={16}/>Reset</button><button onClick={onClose}>Cancel</button><button className="indicator-apply" onClick={save}><Check size={17}/>Apply</button></footer></section></div>;
}
