"use client";
import { useEffect, useMemo, useState } from 'react';
import { Newspaper, RefreshCw, ExternalLink, LineChart } from 'lucide-react';
import type { Instrument } from '@/lib/market';
import { matchNewsStocks, type NewsItem } from '@/lib/market-news';
import { StockLogo } from './StockLogo';
import './news-workspace.css';
export function NewsWorkspace({ instruments, onOpenChart }: { instruments: Instrument[]; onOpenChart: (stock: Instrument) => void }) {
 const [items,setItems]=useState<NewsItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[updated,setUpdated]=useState(''),[refresh,setRefresh]=useState(0),[filter,setFilter]=useState('All');
 useEffect(()=>{const controller=new AbortController();fetch('/api/market/news',{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load news');if(controller.signal.aborted)return;setError('');setItems(d.items);setUpdated(d.updatedAt);setNotice(d.stale?'Showing saved headlines. Live refresh is unavailable.':d.unavailableSources?.length?'Some news sources are temporarily unavailable.':'');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});const timer=setTimeout(()=>{setLoading(true);setError('');setRefresh(n=>n+1);},300000);return()=>{controller.abort();clearTimeout(timer);};},[refresh]);
 const rows=useMemo(()=>items.map(i=>({...i,stocks:matchNewsStocks(i.title,instruments)})).filter(i=>filter==='All'||i.sentiment===filter),[items,instruments,filter]);
 return <section className="news-workspace" aria-label="Market news"><header><div><span className="eyebrow">Market pulse</span><h1><Newspaper/> News</h1><p>Important headlines, ranked by impact signals and recency.</p></div><button disabled={loading} onClick={()=>{setLoading(true);setError('');setRefresh(n=>n+1);}}><RefreshCw size={16}/>{loading?'Loading…':'Refresh'}</button></header><p className="news-disclaimer">Sentiment is an automated reading of the headline, not a prediction of stock returns. Read the source for context.</p><div className="news-filters">{['All','Positive','Negative','Mixed','Neutral'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{updated&&<small>Updated {new Date(updated).toLocaleString('en-IN')}</small>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!rows.length&&<p>No recent headlines match this filter.</p>}<div className="news-grid">{rows.map(i=><article key={i.url+i.title}><div className="news-meta"><span className={`news-sentiment news-${i.sentiment.toLowerCase()}`}>{i.sentiment}</span>{i.importance===3&&<span>High impact signal</span>}<time dateTime={i.publishedAt}>{new Date(i.publishedAt).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></div><h2><a href={i.url} target="_blank" rel="noopener noreferrer">{i.title} <ExternalLink size={14}/></a></h2><small>{i.source}</small><div className="news-stocks">{i.stocks.length?i.stocks.map(s=><button key={s.instrumentKey} aria-label={`Open ${s.symbol} chart`} onClick={()=>onOpenChart(s)}><StockLogo {...s} size={28}/><b>{s.symbol}</b><LineChart size={16}/></button>):<small>Market / sector news · no verified stock match</small>}</div></article>)}</div></section>;
}
