export type StudyField = { key: string; label: string; value: number; min?: number; max?: number; step?: number };
export type StudyDefinition = { id: string; name: string; group: string; overlay?: boolean; fields: StudyField[]; volume?: boolean; comparison?: boolean; note?: string; unavailable?: string };
const length=(value=14,label="Length",key="length"):StudyField=>({key,label,value,min:1,max:key==='annual'?100000:key==='levels'?3:500,step:1});
const num=(key:string,label:string,value:number,min=.1,max=20,step=.1):StudyField=>({key,label,value,min,max,step});
const make=(id:string,name:string,group:string,overlay=false,fields:StudyField[]=[length()],extra:Partial<StudyDefinition>={}):StudyDefinition=>({id,name,group,overlay,fields,...extra});
export const STUDIES:StudyDefinition[]=[
 make('smc','SMC Learner','Learning',true,[],{note:'Structure and zone filters are in SMC Learn. No SMC alerts are added.'}),
 make('patterns','Candlestick patterns','Price',true,[],{note:'Classic candle shapes on closed bars. Labels describe the shape only. They are not trade signals.'}),
 ...[5,21,30,50,100,200].map(n=>make(`ema${n}`,`EMA ${n}`,'Trend',true,[length(n)])),
 ...[20,50,200].map(n=>make(`sma${n}`,`SMA ${n}`,'Trend',true,[length(n)])),
 make('ad','Accumulation/Distribution','Volume',false,[],{volume:true}),
 make('asi','Accumulative Swing Index','Momentum',false,[num('limit','Limit move',3,.01,100000,.01)]),
 make('advance-decline','Advance/Decline','Market breadth',false,[],{unavailable:'Requires exchange-wide advancing and declining stock counts, not one stock’s candles.'}),
 make('alma','Arnaud Legoux Moving Average','Trend',true,[length(9),num('offset','Offset',.85,0,1,.05),num('sigma','Sigma',6,1,20,1)]),
 make('aroon','Aroon','Momentum',false,[length(14)]),
 make('adx','Average Directional Index','Momentum',false,[length(14,'DI length'),length(14,'ADX smoothing','smooth')]),
 make('average-price','Average Price','Price',true,[]),
 make('atr','Average True Range','Volatility',false,[length(14)]),
 make('awesome','Awesome Oscillator','Momentum',false,[length(5,'Fast length','fast'),length(34,'Slow length','slow')]),
 make('bop','Balance of Power','Momentum',false,[length(1,'Smoothing')]),
 ...[['bollinger','Bollinger Bands',true],['bbp','Bollinger Bands %B',false],['bbw','Bollinger Bands Width',false]].map(([id,name,overlay])=>make(String(id),String(name),'Volatility',Boolean(overlay),[length(20),num('multiplier','Standard deviations',2)])),
 make('cmf','Chaikin Money Flow','Volume',false,[length(20)],{volume:true}),
 make('chaikin','Chaikin Oscillator','Volume',false,[length(3,'Fast length','fast'),length(10,'Slow length','slow')],{volume:true}),
 make('chaikin-volatility','Chaikin Volatility','Volatility',false,[length(10),length(10,'Rate-of-change length','roc')]),
 make('chande-kroll','Chande Kroll Stop','Trend',true,[length(10,'ATR length'),length(9,'Stop lookback','lookback'),num('multiplier','ATR multiplier',1)]),
 make('cmo','Chande Momentum Oscillator','Momentum',false,[length(9)]),
 make('chop-zone','Chop Zone','Momentum',false,[length(34)],{note:'Nine colour zones from the EMA slope, normalized by the 30-bar price range.'}),
 make('choppiness','Choppiness Index','Volatility',false,[length(14)]),
 make('cci','Commodity Channel Index','Momentum',false,[length(20)]),
 make('connors','Connors RSI','Momentum',false,[length(3,'Price RSI','length'),length(2,'Streak RSI','streak'),length(100,'Percent rank','rank')]),
 make('coppock','Coppock Curve','Momentum',false,[length(11,'Short ROC','fast'),length(14,'Long ROC','slow'),length(10,'WMA length')]),
 ...[['correlation-log','Correlation - Log'],['correlation','Correlation Coefficient']].map(([id,name])=>make(id,name,'Comparison',false,[length(20)],{comparison:true,note:'Pearson correlation of aligned closes (log closes for Log). Both symbols’ newest bars are excluded. Comparison history refreshes every 60 seconds.'})),
 make('dpo','Detrended Price Oscillator','Momentum',false,[length(20)],{note:'Unshifted causal output; no future candles are read.'}),
 make('dmi','Directional Movement','Momentum',false,[length(14,'DI length'),length(14,'ADX smoothing','smooth')]),
 make('donchian','Donchian Channels','Trend',true,[length(20)]),
 make('dema','Double EMA','Trend',true,[length(9)]),
 make('eom','Ease Of Movement','Volume',false,[length(14),num('divisor','Volume divisor',10000,1,100000000,1)],{volume:true}),
 make('force','Elder’s Force Index','Volume',false,[length(13)],{volume:true}),
 make('ema-cross','EMA Cross','Trend',true,[length(9,'Fast length','fast'),length(26,'Slow length','slow')]),
 make('envelopes','Envelopes','Trend',true,[length(20),num('percent','Envelope %',2.5,.01,100,.1)]),
 make('fisher','Fisher Transform','Momentum',false,[length(9)]),
 make('guppy','Guppy Multiple Moving Average','Trend',true,[],{note:'EMA groups: 3, 5, 8, 10, 12, 15 and 30, 35, 40, 45, 50, 60.'}),
 make('historical-volatility','Historical Volatility','Volatility',false,[length(20),length(252,'Periods per year','annual')],{note:'Annualized log-return deviation. Adjust periods per year for the chosen timeframe.'}),
 make('hma','Hull Moving Average','Trend',true,[length(9)]),
 make('ichimoku','Ichimoku Cloud','Trend',true,[length(9,'Conversion length','fast'),length(26,'Base length','slow'),length(52,'Span B length'),length(26,'Displacement','shift')],{note:'Leading spans and lagging close are displaced by bars. Cloud boundaries are drawn as lines.'}),
 make('keltner','Keltner Channels','Volatility',true,[length(20),length(10,'ATR length','atr'),num('multiplier','ATR multiplier',2)]),
 make('klinger','Klinger Oscillator','Volume',false,[length(34,'Fast length','fast'),length(55,'Slow length','slow'),length(13,'Signal length','signal')],{volume:true}),
 make('kst','Know Sure Thing','Momentum',false,[length(9,'Signal length','signal')],{note:'ROC lengths 10/15/20/30, smoothing 10/10/10/15; weights 1/2/3/4.'}),
 make('lsma','Least Squares Moving Average','Trend',true,[length(25)]),
 make('linreg','Linear Regression Curve','Trend',true,[length(14)]),
 make('slope','Linear Regression Slope','Momentum',false,[length(14)]),
 make('ma-cross','MA Cross','Trend',true,[length(9,'Fast length','fast'),length(26,'Slow length','slow')]),
 make('ma-ema-cross','MA with EMA Cross','Trend',true,[length(10,'SMA length','fast'),length(10,'EMA length','slow')]),
 make('macd','MACD','Momentum',false,[length(12,'Fast length','fast'),length(26,'Slow length','slow'),length(9,'Signal length','signal')]),
 make('majority','Majority Rule','Momentum',false,[length(14)]),
 make('mass','Mass Index','Volatility',false,[length(25,'Sum length'),length(9,'EMA length','smooth')]),
 make('mcginley','McGinley Dynamic','Trend',true,[length(14)]),
 make('median','Median Price','Price',true,[]),
 make('momentum','Momentum','Momentum',false,[length(10)]),
 make('mfi','Money Flow Index','Volume',false,[length(14)],{volume:true}),
 make('ma','Moving Average','Trend',true,[length(20)]),
 make('kama','Moving Average Adaptive','Trend',true,[length(10),length(2,'Fast length','fast'),length(30,'Slow length','slow')]),
 make('ma-channel','Moving Average Channel','Trend',true,[length(20)]),
 make('ma-double','Moving Average Double','Trend',true,[length(9,'First length','fast'),length(21,'Second length','slow')]),
 make('ema','Moving Average Exponential','Trend',true,[length(9)]),
 make('hamming','Moving Average Hamming','Trend',true,[length(14)]),
 make('ma-multiple','Moving Average Multiple','Trend',true,[length(9,'First length','fast'),length(21,'Second length','slow'),length(50,'Third length','length'),length(200,'Fourth length','fourth')]),
 make('ma-triple','Moving Average Triple','Trend',true,[length(9,'First length','fast'),length(21,'Second length','slow'),length(50,'Third length')]),
 make('wma','Moving Average Weighted','Trend',true,[length(9)]),
 make('net-volume','Net Volume','Volume',false,[],{volume:true,note:'Up/down classification uses close versus previous close; it is not bid/ask order flow.'}),
 make('obv','On Balance Volume','Volume',false,[],{volume:true}),
 make('sar','Parabolic SAR','Trend',true,[num('start','Start',.02,.001,1,.01),num('increment','Increment',.02,.001,1,.01),num('maximum','Maximum',.2,.01,1,.01)]),
 make('pivots','Pivot Points Standard','Price',true,[length(3,'Support/resistance levels','levels')],{note:'Classic pivots from the previous complete IST session. Daily charts use the previous daily candle.'}),
 make('opening-range','Opening Range','Price',true,[],{note:'9:15–9:30 IST high and low, extended to 15:30. Needs a 15-minute chart or lower.'}),
 make('previous-day','Previous day','Price',true,[],{note:'Yesterday’s high, low and close. Tap a label to set a price alert at that level.'}),
 make('prior-levels','Prior highs and lows','Price',true,[
  {key:'day',label:'Previous day',value:1,min:0,max:1,step:1},
  {key:'week',label:'Previous week',value:1,min:0,max:1,step:1},
  {key:'month',label:'Previous month',value:1,min:0,max:1,step:1},
  {key:'year',label:'Previous financial year',value:0,min:0,max:1,step:1},
  {key:'custom',label:'Daily candles back',value:0,min:0,max:500,step:1},
  {key:'high',label:'High',value:1,min:0,max:1,step:1},
  {key:'low',label:'Low',value:1,min:0,max:1,step:1},
  {key:'open',label:'Open',value:0,min:0,max:1,step:1},
  {key:'close',label:'Close',value:0,min:0,max:1,step:1},
 ],{note:'Day is purple, week is blue, month is black. Turn off a period to hide it. Financial year is April to March. Daily candles back marks one older daily candle.'}),
 make('price-channel','Price Channel','Trend',true,[length(20)]),
 make('price-oscillator','Price Oscillator','Momentum',false,[length(12,'Fast length','fast'),length(26,'Slow length','slow')]),
 make('pvt','Price Volume Trend','Volume',false,[],{volume:true}),
 make('roc','Rate Of Change','Momentum',false,[length(9)]),
 ...['ratio','spread'].map(id=>make(id,id==='ratio'?'Ratio':'Spread','Comparison',false,[],{comparison:true,note:'Selected symbol divided by / minus the comparison symbol. Exact candle timestamps only; newest bars excluded. Comparison history refreshes every 60 seconds.'})),
 make('rsi','Relative Strength Index','Momentum',false,[length(14),length(14,'Smoothing length','smooth'),num('upper','Upper level',70,1,100,1),num('lower','Lower level',30,0,99,1)]),
 make('rvi','Relative Vigor Index','Momentum',false,[length(10)]),
 make('relative-volatility','Relative Volatility Index','Volatility',false,[length(10,'Deviation length'),length(14,'Smoothing length','smooth')]),
 make('smi','SMI Ergodic Indicator/Oscillator','Momentum',false,[length(5,'Fast length','fast'),length(20,'Slow length','slow'),length(5,'Signal length','signal')]),
 make('smma','Smoothed Moving Average','Trend',true,[length(7)]),
 make('stddev','Standard Deviation','Volatility',false,[length(20)]),
 make('stderr','Standard Error','Volatility',false,[length(20)]),
 make('stderr-bands','Standard Error Bands','Volatility',true,[length(20),num('multiplier','Error multiplier',2)]),
 make('stochastic','Stochastic','Momentum',false,[length(14),length(3,'%K smoothing','smooth'),length(3,'%D smoothing','signal')]),
 make('stoch-rsi','Stochastic RSI','Momentum',false,[length(14,'RSI length'),length(14,'Stochastic length','stoch'),length(3,'%K smoothing','smooth'),length(3,'%D smoothing','signal')]),
 make('supertrend','SuperTrend','Trend',true,[length(10,'ATR length'),num('multiplier','ATR multiplier',3)]),
 make('trend-strength','Trend Strength Index','Momentum',false,[length(14)],{note:'Pearson correlation between closing price and bar index.'}),
 make('tema','Triple EMA','Trend',true,[length(9)]),
 make('trix','TRIX','Momentum',false,[length(18)]),
 make('tsi','True Strength Index','Momentum',false,[length(13,'Fast length','fast'),length(25,'Slow length','slow'),length(13,'Signal length','signal')]),
 make('typical','Typical Price','Price',true,[]),
 make('ultimate','Ultimate Oscillator','Momentum',false,[length(7,'Short length','fast'),length(14,'Medium length'),length(28,'Long length','slow')]),
 ...[['vol-close','Volatility Close-to-Close'],['vol-zero','Volatility Zero Trend Close-to-Close'],['vol-ohlc','Volatility O-H-L-C']].map(([id,name])=>make(id,name,'Volatility',false,[length(20),length(252,'Periods per year','annual')],{note:'Annualized volatility. Set periods per year to match the chart interval.'})),
 make('vol-index','Volatility Index','Volatility',false,[],{unavailable:'The reference does not identify which Volatility Index formula it uses. ATR and historical-volatility studies are available separately.'}),
 make('volume','Volume','Volume',false,[length(9,'Average length')],{volume:true}),
 make('volume-oscillator','Volume Oscillator','Volume',false,[length(5,'Fast length','fast'),length(10,'Slow length','slow')],{volume:true}),
 make('vpvr','Volume Profile Visible Range','Volume',true,[{...length(24,'Rows','rows'),min:8,max:80}],{volume:true,note:'Approximate volume-at-price from visible OHLCV candles; not exchange tick-level volume.'}),
 make('vortex','Vortex Indicator','Momentum',false,[length(14)]),
 make('vwap','VWAP','Volume',true,[],{volume:true,note:'Resets each IST trading session. Requires actual candle volume.'}),
 make('anchored-vwap','Anchored VWAP','Volume',true,[],{volume:true,note:'Tap a candle to start VWAP from that bar. Requires traded volume.'}),
 make('vwma','VWMA','Volume',true,[length(20)],{volume:true}),
 make('williams','Williams %R','Momentum',false,[length(14)]),
 make('alligator','Williams Alligator','Trend',true,[length(13,'Jaw length'),length(8,'Teeth length','teeth'),length(5,'Lips length','lips')],{note:'Smoothed median-price averages displaced by 8/5/3 bars.'}),
 make('fractals','Williams Fractal','Price',true,[{...length(2,'Bars each side'),max:10}],{note:'A mark appears only after the right-side bars close; the last forming candle cannot confirm it.'}),
 make('zigzag','Zig Zag','Trend',true,[num('percent','Reversal %',5,.1,50,.1)],{note:'Historical turns confirm after the reversal threshold. The latest leg changes with price; not an alert signal.'}),
];
export type StudyConfig={inputs:Record<string,number>;source:string;smoothing:string;hidden:boolean;timeframes:string[];colors:string[];width:number;dash:number;showValue:boolean;opacity:number;comparisonKey?:string};
export const STUDY_COLORS=['#8054da','#e89824','#12a58a','#ec5475','#289cdb','#ac69bb','#536987'];
export const SOURCES=['close','open','high','low','hl2','hlc3','ohlc4'];
export const TIMEFRAMES=['1m','3m','5m','15m','30m','1h','1D','1W','1M','1Y'];
export function studyDefaults(id:string):StudyConfig {const d=STUDIES.find(s=>s.id===id),colors=[...STUDY_COLORS];const primary:Record<string,string>={ema5:'#0ea5e9',ema21:'#ff8a00',ema30:'#22c55e',ema50:'#8b5cf6',ema100:'#f97316',ema200:'#e11d48',sma20:'#14b8a6',sma50:'#64748b',sma200:'#8291aa',vwap:'#d946ef',macd:'#2563eb'};if(primary[id])colors[0]=primary[id];if(['supertrend','volume','net-volume','awesome'].includes(id)){colors[0]='#12a58a';colors[1]='#ec5475';}if(id==='volume')colors[2]='#c69759';return {inputs:Object.fromEntries((d?.fields??[]).map(f=>[f.key,f.value])),source:'close',smoothing:id==='rsi'?'SMA':'None',hidden:false,timeframes:[],colors,width:1,dash:0,showValue:!id.startsWith('ema'),opacity:100};}
export function normalizeStudy(id:string,value:unknown):StudyConfig {
 const base=studyDefaults(id),v={...(value&&typeof value==='object'?value:{})} as Partial<StudyConfig>,d=STUDIES.find(s=>s.id===id);
 if(typeof v.showValue!=='boolean')v.showValue=base.showValue;
 for(const f of d?.fields??[]){const n=Number(v.inputs?.[f.key]);base.inputs[f.key]=Number.isFinite(n)?Math.min(f.max??500,Math.max(f.min??1,f.step===1?Math.round(n):n)):f.value;}
 return {...base,source:SOURCES.includes(v.source??'')?v.source!:'close',smoothing:['None','SMA','EMA','RMA','WMA'].includes(v.smoothing??'')?v.smoothing!:base.smoothing,hidden:v.hidden===true,timeframes:Array.isArray(v.timeframes)?TIMEFRAMES.filter(t=>v.timeframes!.includes(t)):[],colors:base.colors.map((c,i)=>/^#[\da-f]{6}$/i.test(v.colors?.[i]??'')?v.colors![i]:c),width:[1,2,3,4].includes(v.width??0)?v.width!:1,dash:[0,1,2,3,4].includes(v.dash??-1)?v.dash!:0,showValue:v.showValue!==false,opacity:Math.max(10,Math.min(100,Number(v.opacity)||100)),comparisonKey:typeof v.comparisonKey==='string'&&/^(NSE_EQ|NSE_INDEX|BSE_INDEX)\|[\w .-]{1,80}$/.test(v.comparisonKey)?v.comparisonKey:undefined};
}
export function studyTitle(id:string,c=studyDefaults(id)){const d=STUDIES.find(s=>s.id===id);if(/^(ema|sma)\d+$/.test(id))return `${id.startsWith('ema')?'EMA':'SMA'} ${c.inputs.length}`;if(id==='rsi')return `RSI ${c.inputs.length}${c.smoothing!=='None'?` ${c.smoothing} ${c.inputs.smooth??c.inputs.length}`:''}`;if(id==='adx')return `ADX ${c.inputs.length} ${c.inputs.smooth}`;if(id==='volume')return `Volume SMA ${c.inputs.length}`;return d?.name??id;}
